export enum BlockchainStatusType {
  NEW = 'NEW',
  READY_FOR_GENERATE = 'READY_FOR_GENERATE',
  WAITING_BLOCKCHAIN = 'WAITING_BLOCKCHAIN',
  DONE = 'DONE',
  READY_TO_REMOVE = 'READY_TO_REMOVE',
  REMOVED = 'REMOVED',
  ERROR = 'ERROR',
  FAILED = 'FAILED',
  CANCELED = 'CANCELED',
}
